# Generated by Django 2.2 on 2019-04-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('drink_name', models.CharField(max_length=75)),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingred_name', models.CharField(max_length=75)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.MenuItem')),
                ('snack_name', models.CharField(max_length=75)),
                ('reccomend', models.ManyToManyField(to='menu.Drink')),
            ],
            bases=('menu.menuitem',),
        ),
    ]
